////////////////////////////////////////////////////////////////////////////////
//                    DO NOT EDIT THIS FILE!                                //
////////////////////////////////////////////////////////////////////////////////

// このファイルは編集しないでください！

//
// [Simple malloc]
//
// This is an example, straightforward implementation of malloc.
//

// [簡易的なmalloc]
// これは、malloc（メモリ割り当て関数）のシンプルで直接的な実装例です。

#include <assert.h>   // assert() 関数のために必要 (デバッグ用のアサート)
#include <math.h>     // 数学関数 (このコードでは直接使われていませんが、一般的なインクルード)
#include <stdint.h>   // 固定幅整数型 (uint8_t など) のために必要
#include <stdio.h>    // 標準入出力 (printf など) のために必要
#include <stdlib.h>   // 一般ユーティリティ関数 (NULL, size_t など) のために必要
#include <string.h>   // 文字列操作関数 (memcpy など) のために必要
#include <sys/mman.h> // mmap() / munmap() 関数のために必要 (システムからメモリを要求・解放するため)
#include <sys/time.h> // 時刻関連関数 (このコードでは直接使われていませんが、一般的なインクルード)

// システムからメモリ領域を割り当てる関数（mmap() を使用）
void *mmap_from_system(size_t size);
// システムにメモリ領域を解放する関数（munmap() を使用）
void munmap_to_system(void *ptr, size_t size);

// 各オブジェクト（割り当てられたメモリ）や空きスロット（利用可能なメモリ）には、その直前にメタデータがあります。
//
// ... | m | object | m | free slot | m | free slot | m | object | ...
//
// ここで、|m| はメタデータを示します。メタデータは2つの目的のために必要です。
//
// 1) 割り当てられたオブジェクトの場合：
//    * |size| はオブジェクトのサイズを示します。|size| にはメタデータのサイズは含まれません。
//    * |next| は使用されず、NULL に設定されます。
// 2) 空きスロットの場合：
//    * |size| は空きスロットのサイズを示します。|size| にはメタデータのサイズは含まれません。
//    * 空きスロットは単方向連結リスト（これをフリーリストと呼びます）でリンクされています。
//      |next| は次の空きスロットを指します。
typedef struct simple_metadata_t {
  size_t size;                       // このブロックのサイズ（メタデータ自体は含まない）
  struct simple_metadata_t *next;    // 次のフリーリストの要素へのポインタ (空きスロットの場合のみ使用)
} simple_metadata_t;

// 簡易版 malloc のグローバル情報。
//    * |free_head| は最初の空きスロットを指します。
//    * |dummy| はダミーの空きスロットです（フリーリストの実装を簡単にするためにのみ使用されます）。
typedef struct simple_heap_t {
  simple_metadata_t *free_head; // フリーリストの先頭へのポインタ
  simple_metadata_t dummy;      // ダミーノード（フリーリストの操作を簡素化するため）
} simple_heap_t;

simple_heap_t simple_heap; // グローバルなヒープ情報構造体

// フリーリストの先頭に空きスロットを追加します。
void simple_add_to_free_list(simple_metadata_t *metadata) {
  assert(!metadata->next); // 追加しようとしているメタデータのnextがNULLであることを確認（デバッグ用）
  metadata->next = simple_heap.free_head; // 追加するメタデータのnextを現在のフリーリストの先頭に設定
  simple_heap.free_head = metadata;       // フリーリストの先頭を新しく追加したメタデータに更新
}

// フリーリストから空きスロットを削除します。
void simple_remove_from_free_list(simple_metadata_t *metadata,
                                   simple_metadata_t *prev) {
  if (prev) { // 削除するスロットの前のスロット（prev）が存在する場合
    prev->next = metadata->next; // prevのnextを、削除するスロットのnextに繋ぎ変える
  } else {    // 削除するスロットがフリーリストの先頭だった場合
    simple_heap.free_head = metadata->next; // フリーリストの先頭を、削除するスロットのnextに更新
  }
  metadata->next = NULL; // 削除されたスロットのnextをNULLに設定（安全のため）
}

// 各チャレンジの最初に呼び出されます。
void simple_initialize() {
  simple_heap.free_head = &simple_heap.dummy; // フリーリストの先頭をダミーノードに設定
  simple_heap.dummy.size = 0;                 // ダミーノードのサイズは0
  simple_heap.dummy.next = NULL;              // ダミーノードのnextはNULL
}

// オブジェクトが割り当てられるたびに呼び出されます。
// |size| は8バイトの倍数であり、8 <= |size| <= 4000 の範囲であることが保証されます。
// mmap_from_system / munmap_to_system 以外のライブラリ関数は使用できません。
void *simple_malloc(size_t size) {
  simple_metadata_t *metadata = simple_heap.free_head; // フリーリストの先頭から探索を開始
  simple_metadata_t *prev = NULL;                      // 現在のメタデータの前のメタデータを保持するポインタ
  // First-fit（初回適合）: オブジェクトが収まる最初の空きスロットを見つけます。
  while (metadata && metadata->size < size) { // メタデータが存在し、かつそのサイズが要求されたサイズより小さい間繰り返す
    prev = metadata;                          // 現在のメタデータをprevに保存
    metadata = metadata->next;                // 次のフリーリストの要素へ移動
  }

  if (!metadata) { // 適切なサイズの空きスロットが見つからなかった場合
    // 利用可能な空きスロットがありませんでした。
    // mmap_from_system() を呼び出して、システムから新しいメモリ領域を要求する必要があります。
    //
    //     | metadata | free slot |
    //     ^
    //     metadata
    //     <---------------------->
    //           buffer_size
    //
    size_t buffer_size = 4096; // 新しく要求するメモリ領域のサイズ（4KB）
    simple_metadata_t *metadata = // システムからメモリを割り当て、その先頭をメタデータとして扱う
        (simple_metadata_t *)mmap_from_system(buffer_size);
    metadata->size = buffer_size - sizeof(simple_metadata_t); // 新しいスロットのサイズを設定（メタデータのサイズ分を引く）
    metadata->next = NULL; // 新しいスロットのnextをNULLに設定
    // このメモリ領域をフリーリストに追加します。
    simple_add_to_free_list(metadata);
    // これで、simple_malloc() を再度試行します。これは成功するはずです。
    return simple_malloc(size);
  }

  // |ptr| は割り当てられたオブジェクトの開始位置です。
  //
  // ... | metadata | object | ...
  //     ^          ^
  //     metadata   ptr
  void *ptr = metadata + 1; // メタデータの直後がオブジェクトの開始位置
  size_t remaining_size = metadata->size - size; // 空きスロットの残りのサイズを計算
  // フリーリストから空きスロットを削除します。
  simple_remove_from_free_list(metadata, prev);

  if (remaining_size > sizeof(simple_metadata_t)) {
    // 割り当てられたオブジェクトのメタデータを縮小し、
    // remaining_size に対応する残りの領域を分離します。
    // もし remaining_size が新しいメタデータを作成するのに十分な大きさでなければ、
    // このコードパスは実行されず、その領域は割り当てられたオブジェクトの一部として管理されます。
    metadata->size = size; // 割り当てられたオブジェクトのメタデータのサイズを、要求されたサイズに更新
    // 残りの空きスロットのために新しいメタデータを作成します。
    //
    // ... | metadata | object | metadata | free slot | ...
    //     ^          ^        ^
    //     metadata   ptr      new_metadata
    //                <------><---------------------->
    //                  size      remaining size
    simple_metadata_t *new_metadata = (simple_metadata_t *)((char *)ptr + size); // 割り当てたオブジェクトの直後が新しいメタデータの開始位置
    new_metadata->size = remaining_size - sizeof(simple_metadata_t); // 新しいフリースロットのサイズを設定
    new_metadata->next = NULL; // 新しいフリースロットのnextをNULLに設定
    // 残りの空きスロットをフリーリストに追加します。
    simple_add_to_free_list(new_metadata);
  }
  return ptr; // 割り当てられたオブジェクトの開始位置を返す
}

// オブジェクトが解放されるたびに呼び出されます。
// mmap_from_system / munmap_to_system 以外のライブラリ関数は使用できません。
void simple_free(void *ptr) {
  // メタデータを探します。メタデータはオブジェクトの直前に配置されています。
  //
  // ... | metadata | object | ...
  //     ^          ^
  //     metadata   ptr
  simple_metadata_t *metadata = (simple_metadata_t *)ptr - 1; // オブジェクトの開始位置から1つ前（メタデータ分）に戻ってメタデータを取得
  // フリーリストに空きスロットを追加します。
  simple_add_to_free_list(metadata);
}

// 各チャレンジの最後に呼び出されます。
void simple_finalize() {
  // 現時点では何もありません。
  // 必要であれば、何か追加しても構いません！
}